<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('courses')->insert([
            [
                'course_id' => 1,
                'name' => 'Design systems desde 0 en Figma',
                'cover' => 'png/course-design-systems-figma.png',
                'short_description' => 'Aprendé desde 0 cómo armar un sistema de diseño en Figma, desde por qué necesitarías uno hasta las mejores prácticas utilizadas por equipos de diseño de todo el mundo en la actualidad.',
                'description' => 'Aprendé desde 0 cómo armar un sistema de diseño en Figma, desde por qué necesitarías uno hasta las mejores prácticas utilizadas por equipos de diseño de todo el mundo en la actualidad.Desarrollar sistemas de diseño que calcen con tu proyecto ahorra muchísimo los tiempos de iteración y problemas que pueden ocurrir al crear productos digitales.Por todo ello, con este curso de sistemas de diseño en Figma aprenderás a crear los componentes, patrones y herramientas necesarias para agilizar tus procesos y las experiencias digitales que quieres crear.Junto a Julia Lopez, profesora del curso y Product Designer en Mercado Libre, conocerás qué elementos componen un design system, cómo crear la estructura del mismo y qué se necesita establecer en la guía de estilo de tu sistema de diseño.A lo largo de este curso, aprenderás los beneficios de crear un design system para tus proyectos digitales y serás capaz de crear uno acorde a tu usuario y tu producto digital.',
                'price' => 850000,
                'rating' => '4.8',
                'students' => 14638,
                'duration' => 5,
                'level' => 'intermedio',
                'requirements' => 'Se necesitan conocimientos intermedios en Figma, tales como autolayout, grilla, variables, constraints y prototipado.',
                'tags' => 'UX/UI.UI.Figma',
                'learnings' => 'Qué es un Design System y cuándo se necesita uno.Construir componentes que forman parte de un Design System.Plugins de Figma que para agilizar el proceso.Handoff: buenas prácticas al momento de colaborar con developers',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
                'teacher_id'=> 1,

            ],
            [
                'course_id' => 2,
                'name' => 'Cómo organizar tu CSS con la metodología BEM',
                'cover' => 'png/course-css-bem.png',
                'short_description' => 'Aprendé a optimizar tus proyectos frontend con un sistema robusto, escalable, mantenible en el tiempo y con una serie de reglas fáciles de seguir: BEM (Block Element Modifier).',
                'description' => 'Aprendé a optimizar tus proyectos frontend con un sistema robusto, escalable, mantenible en el tiempo y con una serie de reglas fáciles de seguir: BEM (Block Element Modifier).Cuando haces un proyecto, a nivel front end, pasas mucho tiempo maquetando y manteniendo el código CSS.Es una tarea difícil cuando hay selectores anidados que influyen en varios sitios de la web y pueden romper estilos de otras secciones.No sabes qué puedes editar o borrar.Además, como no está bien estructurado el código, terminas añadiendo !important por todos lados...¿te suena de algo?.Con este curso, ya no tendrás que sufrir más con ese tipo de problemas.Mejorarás tu metodología de trabajo en el desarrollo web frontend y optimizarás el tiempo que te lleva cuando un cliente pida modificaciones en tus proyectos.Si lo que buscas es poder escribir código que sea lo más transparente y auto-documentado posible (transparencia en el sentido de que es clara y obvia en su intención, y auto-documentado porque no tenemos que perder tiempo escribiendo y leyendo documentación extensa y complementaria), la metodología BEM es para vos.',
                'price' => 450000,
                'rating' => '4.5',
                'students' => 12631,
                'duration' => 3,
                'level' => 'intermedio',
                'requirements' => 'Se necesitan conocimientos intermedios en HTML y CSS, ya que no se verá cómo utilizar esas tecnologías en este curso.',
                'tags' => 'Frontend.CSS.Metodología',
                'learnings' => 'Qué es la nomenclatura BEM y cómo se utiliza.La metodología BEMIT (BEM CSS + ITCSS).Escribir CSS de manera escalable a largo plazo.Código limpio y buenas prácticas al maquetar',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 2,
                'teacher_id'=> 2,

            ],
            [
                'course_id' => 3,
                'name' => 'Cómo diseñar interfaces web responsive haciendo uso de grillas',
                'cover' => 'png/course-responsive-grid.png',
                'short_description' => 'Aprendé todo sobre el uso de las grillas en el diseño de interfaces web y cómo volver tus diseños responsive.',
                'description' => 'Aprendé todo sobre el uso de las grillas en el diseño de interfaces web y cómo volver tus diseños responsive.Las grillas no solo ayudan cuando se trata de crear un diseño coherente, también son la columna vertebral cuando se trata de diseño responsivo y hacer que tu producto digital brille a través de todos los tamaños de pantalla posibles.Figma es una excelente herramienta para diseñar pantallas de sitios web y aplicaciones, y tiene muchas ventajas sobre otros programas de diseño dedicados a imágenes estáticas.Entre ellas, se encuentra la posibilidad de reutilizar componentes y estilos, de crear prototipos para ver cómo funciona tu diseño antes de desarrollarlo y, por supuesto, la posibilidad de hacer que sea responsive.Este curso en particular tiene como objetivo darte a vos y a tu equipo una idea de cómo deberían verse las pantallas de tu diseño cuando el dispositivo cambia su tamaño.Además, vamos a ir un paso más y ver algo de maquetado básico, para que como diseñador/a UX/UI entiendas realmente la parte técnica que hay detrás del producto que estás construyendo.',
                'price' => 430000,
                'rating' => '4.5',
                'students' => 4539,
                'duration' => 3,
                'level' => 'intermedio',
                'requirements' => 'Se necesitan conocimientos intermedios en Figma, puesto que no se explicará desde 0 cómo utilizar la herramienta (solo las funcionalidades de grilla y autolayout).',
                'tags' => 'UX/UI.UI.Figma',
                'learnings' => 'Cómo diseñar utilizando grillas responsive y adaptables en Figma.Añadir contenido evitando errores comunes de posicionamiento.Aplicación básica de columnas, gutter, margen y filas.Qué son los breakpoints, de dónde vienen y cómo utilizarlos',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
                'teacher_id'=> 1,

            ],
            [
                'course_id' => 4,
                'name' => 'Cómo agregar animaciones a tus webs con GSAP',
                'cover' => 'png/course-gsap.png',
                'short_description' => 'Llevá tu desarrollo front-end al siguiente nivel añadiendo sofisticadas animaciones interactivas a tus proyectos.',
                'description' => 'Llevá tu desarrollo front-end al siguiente nivel añadiendo sofisticadas animaciones interactivas a tus proyectos.GSAP (GreenSock Animation Platform) es una colección de herramientas que te permitirán dar rienda suelta a tu creatividad y programar animaciones con líneas de tiempo fluidas.Está diseñado para ofrecer rendimiento, compatibilidad y ser fácil de usar.No es de extrañar que más de 7 millones de sitios web utilicen GSAP para dar una capa extra de profesionalismo y creatividad a sus proyectos.Este curso te enseñará todo lo que necesitas para una base sólida en GSAP.Al finalizar este curso, tendrás todos los conocimientos necesarios para crear impresionantes animaciones con JavaScript.',
                'price' => 450000,
                'rating' => '4.5',
                'students' => 14621,
                'duration' => 5,
                'level' => 'avanzado',
                'requirements' => 'Se necesitan conocimientos avanzados en HTML, CSS y JavaScript, ya que no se verá cómo utilizar esas tecnologías en este curso.',
                'tags' => 'Frontend.GSAP.Animaciones.JavaScript',
                'learnings' => 'Cómo crear sofisticados componentes UI con GSAP.Darle profesionalidad a tus webs con animaciones.Cómo crear líneas de tiempo de animación complejas.Cómo poner en práctica lo aprendido en webs reales',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 2,
                'teacher_id'=> 2,

            ],
            [
                'course_id' => 5,
                'name' => 'Diseñar experiencias digitales siguiendo pautas de accesibilidad',
                'cover' => 'png/course-accesibility.png',
                'short_description' => 'Aprendé a aplicar los principios de la accesibilidad web (Web Content Accessibility Guidelines) en tus diseños y la importancia de considerar la diversidad de necesidades que tus creaciones cubren.',
                'description' => 'Aprendé a aplicar los principios de la accesibilidad web (Web Content Accessibility Guidelines) en tus diseños y la importancia de considerar la diversidad de necesidades que tus creaciones cubren.Al desarrollar frameworks, estructuras, diseños y aplicaciones, estamos pensando en atender las necesidades específicas de un colectivo.En este curso de accesibilidad para web, comprenderás la importancia de considerar la diversidad de necesidades que tus creaciones cubren y aprenderás a aplicar los principios del diseño web inclusivo en tus proyectos a futuro.Junto a Eugenia Casabona, profesora del curso y Lead UX Researcher en Accenture, aprenderás técnicas de accesibilidad y usabilidad a partir de ejemplos reales de diseño inclusivo.Asimismo, aprenderás a evaluar tus proyectos web usando metodologías y herramientas estandarizadas que te acercarán cada vez más a la inclusión.Este curso se basa en las últimas guidelines WCAG 2.1 y 2.2, por lo que obtendrás la información más reciente.Cada vez que se publiquen nuevas guidelines, este curso también se actualizará.¡Mantenete al día!',
                'price' => 470000,
                'rating' => '4.3',
                'students' => 11143,
                'duration' => 5,
                'level' => 'inicial',
                'requirements' => 'No se necesitan conocimientos en accesibilidad digital ni usabilidad, se verá todo desde 0.',
                'tags' => 'UX/UI.Accesibilidad',
                'learnings' => 'Cómo diseñar pensando en la accesibilidad.Fundamentos de la accesibilidad: cuándo, cómo y por qué.Mejores prácticas y estrategias para diseñar de manera inclusiva.Ejemplos prácticos del día a día de un diseñador UX profesional',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
                'teacher_id'=> 3,

            ],
            [
                'course_id' => 6,
                'name' => 'Agregá animaciones 3D a tus webs con Three.js',
                'cover' => 'png/course-three.png',
                'short_description' => 'Aprendé a crear sitios web 3D envolventes y creativos con la librería Three.js.',
                'description' => 'Aprendé a crear sitios web 3D envolventes y creativos con la librería Three.js.¿Has querido aprender a desarrollar en 3D para la web y te has perdido entre tanta información? Ahí es donde entra este curso.Utilizaremos una poderosa librería llamada Three.js, una de las más usadas en el entorno web para poder renderizar 3D en el navegador, cuenta con una documentación genial y con grandiosos ejemplos que puedes explorar.Si eres desarrollador web, tienes conocimientos de programación básica o simplemente quieres aprender a trabajar con 3D en la web, este curso es para vos.Te guiaré paso a paso creando ejercicios simples que nos ayudarán a conocer nuestra librería, y aprenderás a mezclar unas librerías que van genial con three.js y el desarrollo 3D en la web como lo son eventemitter3 y tweens.js.Este curso te enseñará todo lo que necesitas para una base sólida en Three.js.Al finalizar este curso, serás capaz de crear gráficos en 3D impresionantes y experiencias interactivas en la web.',
                'price' => 1020000,
                'rating' => '4.5',
                'students' => 16121,
                'duration' => 5,
                'level' => 'avanzado',
                'requirements' => 'Se necesitan conocimientos avanzados en HTML, CSS y JavaScript, ya que no se verá cómo utilizar esas tecnologías en este curso.',
                'tags' => 'Frontend.ThreeJS.Animaciones.JavaScript',
                'learnings' => 'Fundamentos teóricos de la librería ThreeJS.Cómo instalar ThreeJS e importarlo a tu proyecto.Cómo recorrer la escena con movimientos de la cámara en 3D.Cómo añadir elementos web HTML y CSS a tu escena',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 2,
                'teacher_id'=> 2,

            ],
            [
                'course_id' => 7,
                'name' => 'Creá Web APIs RESTful con ASP.NET',
                'cover' => 'png/course-net.png',
                'short_description' => '¡Aprendé a construir y publicar cualquier Web API que te propongas!',
                'description' => 'Aprende a desarrollar Web APIs con ASP.NET Core desde cero con este increíble curso.Vamos a ver todo el ciclo de vida del desarrollo de un Web API, desde crear la solución, desarrollar los endpoints, trabajar la manipulación de recursos, hasta su puesta en publicación en Azure.Aprende también a utilizar Azure DevOps para configurar un pipeline de Continuous Integration y Continuous Delivery, para poder publicar tus proyectos desde su código fuente en Github, Bitbucket, o cualquier otro proveedor de repositorios de GIT.Los Web APIs son fundamentales en el desarrollo web moderno.Ya que nos permiten centralizar y proteger la lógica de nuestras soluciones.Además de que es en un Web API que típicamente tenemos acceso a una base de datos central con la cual todos tus usuarios se pueden comunicar.Ya sea que construyas una red social, una aplicación de deliveries, o incluso una app de oficina, un Web API te permite trabajar el back-end de aplicaciones móviles (Android, iOS, MAUI, etc.), web (React, Angular, Blazor, Vue, etc.), desktop, entre otros.Si programás en .NET y querés aprender a construir Web APIs, este curso es para vos.',
                'price' => 950000,
                'rating' => '4.8',
                'students' => 9423,
                'duration' => 5,
                'level' => 'avanzado',
                'requirements' => 'Se necesitan conocimientos avanzados de C#.',
                'tags' => 'Bakend.APIs.APIs RESTful.ASP.NET',
                'learnings' => 'Construir Web APIs con NET Core.Publicar Web APIs en Azure.Utilizar Azure DevOps para configurar CI/CD.Desarrollar Web APIs RESTful',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 3,
                'teacher_id'=> 4,


            ],
            [
                'course_id' => 8,
                'name' => 'Cómo crear modelos de Machine Learning robustos y consistentes',
                'cover' => 'png/course-machine-learning.png',
                'short_description' => 'Aprende a crear algoritmos de Machine Learning en Python de la mano de expertos en Data Science.',
                'description' => 'Aprende a crear algoritmos de Machine Learning en Python de la mano de expertos en Data Science.En este curso, aprenderás sobre los fundamentos del Machine Learning y su aplicación en la solución de problemas reales mediante el uso de Python.Desde un nivel muy básico y al alcance de todo tipo de perfiles, se explicarán los fundamentos teóricos y matemáticos que se necesitan para comprender en detalle el funcionamiento de los algoritmos de aprendizaje automático y las técnicas de ciencia de datos más importantes en la actualidad.Representaré gráficamente todas las intuiciones matemáticas en las que se fundamenta el Machine Learning, de manera que, cualquier persona pueda comprenderlas y avanzar con las siguientes secciones.Este no es un curso para matemáticos, es un curso para todos aquellos que quieren adentrarse en el dominio del aprendizaje automático aprendiendo unas bases sólidas que le permitan solucionar problemas reales mediante la implementación en Python de las principales técnicas existentes y comprender aquellos algoritmos que surjan en el futuro.La inteligencia Artificial, y más concretamente el Machine Learning, ha sido percibida en muchas ocasiones como una disciplina compleja al alcance de unos pocos profesionales.Este curso ha sido creado para refutar esta creencia y demostrar que cualquier persona con suficiente interés puede convertirse en un profesional del aprendizaje automático.',
                'price' => 1350000,
                'rating' => '4.1',
                'students' => 2424,
                'duration' => 5,
                'level' => 'inicial',
                'requirements' => 'Conocimientos básicos de Python son útiles, pero no excluyentes.',
                'tags' => 'Data.Data Science.Python.Machine Learning',
                'learnings' => 'Dominar el Machine Learning con Python.Crear unos análisis elaborados.Hacer predicciones precisas y acertadas.Conocer las técnicas más avanzadas',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
                'teacher_id'=> 5,


            ],
            [
                'course_id' => 9,
                'name' => 'Cómo validar ideas en 5 días con Design Sprints',
                'cover' => 'png/course-design-sprints.png',
                'short_description' => 'Aprendé a prototipar, testear y validar ideas para el desarrollo de negocios en 5 días con ayuda de la metodología Design Sprint de Google.',
                'description' => 'Prototipar, testear y validar ideas para el desarrollo de negocios en 5 días es posible gracias a la metodología Design Sprint de Google Ventures (GV).Si te interesa encontrar soluciones ágiles y acelerar el crecimiento de tu negocio, este curso de Design Sprint es lo que vos y tu equipo necesitan.Para gestionar de forma eficaz tanto tus productos como tus clientes, es imprescindible entenderlos bien ambos.Esa es la clave de los sprints de diseño, que se llevan a cabo para ayudar a empresas a introducir un producto en un mercado con el mínimo riesgo y suponen una parte esencial del proceso creativo, especialmente de start-ups.En este curso, obtendrás recomendaciones respecto de cómo encarar los desafíos que plantea Design Sprint y potenciar el trabajo en equipo.Comprobarás que es posible idear, prototipar y validar una idea de un proyecto ágil en 5 días y acelerar el desarrollo de tu negocio.Además, aprenderás a ejecutar un plan para cosechar rápidamente la mayor cantidad de información que sea relevante para tu proyecto, reto o modelo de negocio; todo con el fin de realizar las investigaciones necesarias para resolver por fin la duda: ¿debo realizar este proyecto?.Aprendé el proceso que utilizan los equipos de diseño en la actualidad para resolver retos y llevar adelante proyectos eficazmente.',
                'price' => 540000,
                'rating' => '4.1',
                'students' => 10159,
                'duration' => 4,
                'level' => 'intermedio',
                'requirements' => 'Se necesitan conocimientos intermedios en diseño de experiencia de usuario, tales como Design Thinking y todas las fases que componen este proceso.',
                'tags' => 'UX/UI.Metodología',
                'learnings' => 'Comprender el concepto de Design Sprint.Conocer las etapas del proceso de Design Sprint.Identificar elementos del proceso de Design Sprint.Aplicar Design Sprint para las mejoras de productos digitales',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
                'teacher_id'=> 6,


            ],
            [
                'course_id' => 10,
                'name' => 'Cómo crear aplicaciones utilizando el modelo MVC con PHP',
                'cover' => 'png/course-mvc.png',
                'short_description' => 'Incorporá el paradigma modelo-vista-controlador (MVC) a tus proyectos PHP de manera profesional.',
                'description' => 'En la actualidad el requisito más solicitado en los puestos de trabajo como desarrollador web es contar con el conocimiento de la programación orientada a objetos, combinada con la metodología de la estructura modelo vista controlador (MVC).El MVC propone la construcción de tres componentes distintos que son el modelo, la vista y el controlador, es decir, por un lado define componentes para la representación de la información, y por otro lado para la interacción del usuario.Este patrón de arquitectura de software se basa en las ideas de reutilización de código y la separación de conceptos, características que buscan facilitar la tarea de desarrollo de aplicaciones y su posterior mantenimiento.Es por eso que en este curso hemos recopilado la información necesaria para que en poco tiempo puedas aprender este tipo de programación.Llevándote desde lo más básico de PHP, adentrándose en la POO y bases de datos hasta llegar a crear un proyecto completo con el uso de todos estos conocimientos combinados con MVC.Al finalizar serás capaz de entender la programación orientada a objetos no solo en PHP si no en cualquier lenguaje que la utilice, y además tendrás un ejemplo práctico de la implementación del paradigma MVC, para poder desarrollar tu propio framework y tener la capacidad de trabajar en equipo en cualquier empresa de desarrollo que te lo solicite.',
                'price' => 950000,
                'rating' => '4.2',
                'students' => 7423,
                'duration' => 4,
                'level' => 'intermedio',
                'requirements' => 'Se necesitan conocimientos intermedios en PHP, HTML, CSS, MySQL y bases de datos.',
                'tags' => 'Backend.PHP.MVC',
                'learnings' => 'Los conceptos utilizados en el modelo MVC.Crear una aplicación con PHP y el modelo MVC.Repasar conceptos de POO.Cómo estructurar tu proyecto usando este modelo',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 3,
                'teacher_id'=> 4,


            ],
            [
                'course_id' => 11,
                'name' => 'UX Research: llevá adelante investigaciones cuantitativas con encuestas',
                'cover' => 'png/course-quantitative.png',
                'short_description' => 'Aprendé diversos métodos y técnicas de investigación cuantitativa para aplicar al diseño de tus productos y servicios digitales.',
                'description' => 'Entender el comportamiento de los usuarios es de gran importancia para el diseño de productos digitales; validar las hipótesis UX de forma estadística, también.Por ello, en este curso de UX Research aprenderás diversos métodos y técnicas de investigación cuantitativa para aplicar al diseño de tus productos y servicios digitales.Para una mayor especialización, el curso se enfoca en el método de investigación cuantitativa favorito de los equipos de UXR: ¡las encuestas! En ese sentido, a lo largo del curso descubrirás cómo planificar, diseñar y ejecutar encuestas que te permitan validar hipótesis de investigación.Junto a Eugenia Casabona, profesora del curso y Lead UX Researcher en Accenture, aprenderás a definir los objetivos de tu investigación, formular las preguntas y decidir el tipo de respuesta más adecuada en cada caso.Al finalizar este curso de UX Research, habrás aprendido a crear tu propio proyecto de investigación cuantitativa utilizando un canvas de trabajo para la creación de encuestas efectivas.',
                'price' => 830000,
                'rating' => '4.4',
                'students' => 8256,
                'duration' => 5,
                'level' => 'intermedio',
                'requirements' => 'Se necesitan conocimientos intermedios en diseño de experiencia de usuario, especialmente conocimientos generales en UX Research.',
                'tags' => 'UX/UI.UX Research',
                'learnings' => 'En qué consiste la metodología de la investigación cuantitativa.Cómo planificar y diseñar una encuesta en UX Research.En qué escenario utilizar qué método de investigación.Entender cuáles son los riesgos y beneficios de este método',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 1,
                'teacher_id'=> 3,


            ],
            [
                'course_id' => 12,
                'name' => 'Cómo realizar API Testing con Postman',
                'cover' => 'png/course-postman.png',
                'short_description' => 'Aprendé a automatizar con Postman y llevá adelante API/Web Services testing con integración CI/CD.',
                'description' => 'Aprendé a automatizar con Postman y llevá adelante API/Web Services testing con integración CI/CD.POSTMAN es la herramienta de API Testing más usada a nivel mundial que todo tester y developer debe conocer para poder probar y automatizar APIs de una manera rápida y sencilla, su popularidad se ha extendido rápidamente durante los últimos años debido a su simplicidad para manejar todo el ciclo de vida de una API.En este curso vas a aprender a dominar la herramienta en su ultima version 2023 completamente desde cero y conocerás todas las funciones más importantes, trucos y tips que te facilitaran la vida la próxima vez que veas una API RESTFul.Fue diseñado para ir paso a paso para todos los niveles, partiendo desde la instalación, manejo de workspaces, colecciones, variables, API requests, pruebas de APIS con snippets, assertions avanzadas y automatización de ejecución con el collection runner, monitores, Newman, integracion en Jenkins y Azure Devops.Después de este curso, manejarás Postman como un profesional y podrás agregar esta herramienta a tu skillset.',
                'price' => 780000,
                'rating' => '4.1',
                'students' => 8384,
                'duration' => 4,
                'level' => 'inicial',
                'requirements' => 'No se necesitan conocimientos avanzados en programación, pero suman conocimientos básicos de pruebas de software.',
                'tags' => 'Backend.Postman.APIs',
                'learnings' => 'Instalar Postman y manejar las funciones más importantes.Testear APIs con ejemplos del mundo real.Automatizar pruebas de APIs.interpretá las especificaciones de una API REST',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 3,
                'teacher_id'=> 4,


            ],
            [
                'course_id' => 13,
                'name' => 'Cómo extraer datos de la web utilizando Python',
                'cover' => 'png/course-data-python.png',
                'short_description' => 'Aprendé los fundamentos del Web Scraping para extraer y analizar datos de la web con Python.',
                'description' => 'Aprendé los fundamentos del Web Scraping para extraer y analizar datos de la web con Python.En este curso aprenderás cómo automatizar tareas diarias, rutinarias, cotidianas de extracción de datos de internet para su posterior análisis, recolección, estudio o cualquiera sea tu objetivo.Además, conocerás el poder del Web Scraping con cada librería de Python.Aprender Web Scraping no es solo enviar y traer información de la web, es abrir el espectro a la integración con tecnologías complementarias como Power BI u otras herramientas que hoy en día hacen parte de la interconexión del mundo.No importa si eres un científico de datos, un analista de datos o un programador, ¡obtener acceso a los datos que necesita es importante! Esta es la razón por la que algunas de las mejores empresas tales como Walmart, Target y CNN utilizan el Web Scraping: para poder tomar decisiones basadas en datos.Podemos decir que esta es una de sus mejores armas secretas.En este curso aprenderás los fundamentos del Web Scraping, y a utilizar los diferentes frameworks y librerías disponibles en Python para Web Scraping.',
                'price' => 1350000,
                'rating' => '4.3',
                'students' => 3184,
                'duration' => 3,
                'level' => 'inicial',
                'requirements' => 'Conocimientos básicos de Python son útiles, pero no excluyentes.El curso se puede seguir perfectamente aún sin saber programar.',
                'tags' => 'Data.Python.Web Scraping',
                'learnings' => 'Funcionamiento de APIs para el Web Scraping.Extracción de datos de XML.Extracción de datos de JSON.Recolección de datos de forma automática',
                'created_at' => now(),
                'updated_at' => now(),
                'category_id' => 4,
                'teacher_id'=> 5,


            ]

        ]);
    }
}
